### ISSUE TITLE
Why u-boot need patch but Armbian u-boot does not??

### ISSUE THREAD

**Issue by phaitonican** [fb87/nixos-orangepi-5x#6]
Why u-boot need patch but Armbian u-boot does not??

**Comment by fb87** [comment]
Which patch do you mean? If you talk about u-boot v2023, I don't think Armbian use that version. BTW, Nix 23.05 uses quite new compiler which turns some warnings to errors, that's why if you compile u-boot v2017(from rockchip) will fail so patches are required.

**Comment by phaitonican** [comment]
oh I seee. Oh so [Ryans version](https://github.com/ryan4yin/nixos-rk3588) USES u-boot v2017 thatswhy it fail?? Oh I see thank you

**Comment by phaitonican** [comment]
Ok I get it now thanks very much <3.
