### ISSUE TITLE
Can you send me compiled U-Boot?

### ISSUE THREAD

**Issue by phaitonican** [fb87/nixos-orangepi-5x#7]
Hey,

I am trying to get work NixOS on this repo: https://github.com/ryan4yin/nixos-rk3588/pull/40

Unfortunately, I can not compile U-Boot on my system (idk it not work).

I want to ask if you could maybe send me your compiled version of U-Boot with the emmc patch? I would really appreciate it.

Thank you.

**Comment by fb87** [comment]
On the sdimage, the uboot have packed and placed at the first partition, on the firmware dir. Download the image on release page, mount first partition and you can find uboot image there.

**Comment by phaitonican** [comment]
oh i tried this it not work but i will try again let you know thanks

**Comment by phaitonican** [comment]
![20241004_12h15m58s_grim](https://github.com/user-attachments/assets/f01ec662-d569-42db-8e96-e3a6d059d144)

Is it one of these? Im inside first partition but names are strange idk (there is no firmware folder and u-boot-rpiX etc for raspberrypi?) Sorry for ask

**Comment by fb87** [comment]
[u-boot.zip](https://github.com/user-attachments/files/17264827/u-boot.zip)
check this out.

Or you can just add one line like bellow, and then you can build `u-boot` only `nix build .#u-boot` (assuming cross-build on x86_64 with `binfmt.emulatedSystems = [ "aarch64-linux" ];`).

```
diff --git a/flake.nix b/flake.nix
index ad5ed87..457b389 100644
--- a/flake.nix
+++ b/flake.nix
@@ -548,6 +548,7 @@
       formatter.aarch64-linux = pkgs.nixpkgs-fmt;
 
       packages.aarch64-linux.default = nixosConfigurations.live.config.system.build.sdImage;
+      packages.x86_64-linux.u-boot = u-boot;
       packages.aarch64-linux.sdwriter = pkgs.writeScript "flash" ''
         echo "= flash to sdcard (/dev/mmcblk1) if presented, requires sudo as well."
         [ -e /dev/mmcblk1 ] && zstdcat result/sd-image/*.zst | \
```

**Comment by phaitonican** [comment]
Wow thank you very much
